
//----------------------------------------------------
// The following code was automatically generated by Cup.
//----------------------------------------------------

package cup;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int RTBRACE = 25;
  public static final int GRT = 28;
  public static final int GRTEQ = 29;
  public static final int IMPL = 42;
  public static final int RTPRN = 21;
  public static final int _INT = 4;
  public static final int LESS = 26;
  public static final int STRINGCONST = 13;
  public static final int LFTBRACKET = 22;
  public static final int FR = 9;
  public static final int NOT = 34;
  public static final int AND = 32;
  public static final int ELS = 8;
  public static final int INTCONST = 11;
  public static final int RTRN = 47;
  public static final int OR = 33;
  public static final int COMMA = 37;
  public static final int SEMICOL = 36;
  public static final int DIV = 18;
  public static final int MULOP = 17;
  public static final int NUL = 6;
  public static final int ASSIGN = 35;
  public static final int _IF = 7;
  public static final int LESSEQ = 27;
  public static final int ID = 50;
  public static final int DOT = 38;
  public static final int EOF = 0;
  public static final int PRNTLN = 45;
  public static final int error = 1;
  public static final int CLS = 40;
  public static final int MOD = 19;
  public static final int NEQ = 31;
  public static final int BOOLN = 2;
  public static final int _VOID = 48;
  public static final int NW = 49;
  public static final int READLN = 46;
  public static final int ADDOP = 15;
  public static final int LFTPRN = 20;
  public static final int INTRFC = 43;
  public static final int EQL = 30;
  public static final int DBL = 3;
  public static final int DBLCONST = 12;
  public static final int BRK = 39;
  public static final int BOOLCONST = 14;
  public static final int NEWAR = 44;
  public static final int WHLE = 10;
  public static final int STRING = 5;
  public static final int EXTNDS = 41;
  public static final int SUBOP = 16;
  public static final int RTBRC = 23;
  public static final int LFTBRACE = 24;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "BOOLN",
  "DBL",
  "_INT",
  "STRING",
  "NUL",
  "_IF",
  "ELS",
  "FR",
  "WHLE",
  "INTCONST",
  "DBLCONST",
  "STRINGCONST",
  "BOOLCONST",
  "ADDOP",
  "SUBOP",
  "MULOP",
  "DIV",
  "MOD",
  "LFTPRN",
  "RTPRN",
  "LFTBRACKET",
  "RTBRC",
  "LFTBRACE",
  "RTBRACE",
  "LESS",
  "LESSEQ",
  "GRT",
  "GRTEQ",
  "EQL",
  "NEQ",
  "AND",
  "OR",
  "NOT",
  "ASSIGN",
  "SEMICOL",
  "COMMA",
  "DOT",
  "BRK",
  "CLS",
  "EXTNDS",
  "IMPL",
  "INTRFC",
  "NEWAR",
  "PRNTLN",
  "READLN",
  "RTRN",
  "_VOID",
  "NW",
  "ID"
  };
}

